### ISSUE TITLE
don't change application state

### ISSUE THREAD

**Issue by emirikol** [ondrejbartas/rake-progressbar#1]
wouldn't calling STDOUT.fluh when needed be better than changing STDOUT.sync for the whole application?

**Comment by ondrejbartas** [comment]
I change it, tested it and you are right, it is better solution. Before I didn't think about it that way. 

Thank you for your issue,

I fixed it (0.0.3) on rubygems.org

If you have anything else, just ask.

Have a nice day
Ondrej Bartas
