### ISSUE TITLE
Blows up when can't detect terminal size

### ISSUE THREAD

**Issue by duckpond** [ondrejbartas/rake-progressbar#2]
Made my CI machine go all red :(

I hacked it to work by subclassing RakeProgressbar and overriding initialize and inc when Rails.env is 'test'. It'd be nice if it worked out of the box, maybe guarded against detect_terminal_size returning nil.

**Comment by ondrejbartas** [comment]
Sorry for that problem,

I fix it for all environments -> it should be fine now
