### ISSUE TITLE
timezone info

### ISSUE THREAD

**Issue by ripple0328** [ondrejbartas/rake-progressbar#3]
the time display is not localtime

**Comment by ondrejbartas** [comment]
Hello @ripple0328 

where time is displayed in non local time? I looked to code and all times it displays its difference between started time and actual time. I cannot find any time displayed in full time string.

Can you send an example of your issue?

**Comment by ripple0328** [comment]
Thank you for your reply.  I first guess the time should be the time  I spend on the task. but The displayed [remainingTime] and [Time diff] on the right  happen to be same as my local time just diff 8 hour, that is exactly my local timezone (+8). So I make a blind guess, the displayed time is the time when I start to run the task.  By run task more times, and look at the gem code. I realize it's misunderstanding.
Thank you very much. good gem.

**Comment by ondrejbartas** [comment]
:smile: ok

Thank you for this issue and I am closing it.

If you will find something, let me know and I will look at it.

Cheers Ondrej
